# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/qt\flash_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


# Added by buildgui.py script to support pyinstaller
from src.helpers.pyinstaller_helper import PyInstallerHelper

class Ui_FlashDialog(object):
    def setupUi(self, FlashDialog):
        FlashDialog.setObjectName("FlashDialog")
        FlashDialog.resize(571, 426)
        self.verticalLayout = QtWidgets.QVBoxLayout(FlashDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FlashDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pythonPathEdit = QtWidgets.QLineEdit(FlashDialog)
        self.pythonPathEdit.setReadOnly(False)
        self.pythonPathEdit.setObjectName("pythonPathEdit")
        self.horizontalLayout.addWidget(self.pythonPathEdit)
        self.pickPythonButton = QtWidgets.QPushButton(FlashDialog)
        self.pickPythonButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pickPythonButton.setObjectName("pickPythonButton")
        self.horizontalLayout.addWidget(self.pickPythonButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(FlashDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.firmwarePathEdit = QtWidgets.QLineEdit(FlashDialog)
        self.firmwarePathEdit.setReadOnly(False)
        self.firmwarePathEdit.setObjectName("firmwarePathEdit")
        self.horizontalLayout_2.addWidget(self.firmwarePathEdit)
        self.pickFirmwareButton = QtWidgets.QPushButton(FlashDialog)
        self.pickFirmwareButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pickFirmwareButton.setObjectName("pickFirmwareButton")
        self.horizontalLayout_2.addWidget(self.pickFirmwareButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(FlashDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.portComboBox = QtWidgets.QComboBox(FlashDialog)
        self.portComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.portComboBox.setObjectName("portComboBox")
        self.horizontalLayout_4.addWidget(self.portComboBox)
        self.refreshButton = QtWidgets.QPushButton(FlashDialog)
        self.refreshButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(PyInstallerHelper.resource_path("icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_4.addWidget(self.refreshButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.wiringButton = QtWidgets.QPushButton(FlashDialog)
        self.wiringButton.setMinimumSize(QtCore.QSize(200, 0))
        self.wiringButton.setObjectName("wiringButton")
        self.horizontalLayout_4.addWidget(self.wiringButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(FlashDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.outputEdit = QtWidgets.QPlainTextEdit(FlashDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputEdit.sizePolicy().hasHeightForWidth())
        self.outputEdit.setSizePolicy(sizePolicy)
        self.outputEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.outputEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputEdit.setLineWidth(1)
        self.outputEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.outputEdit.setUndoRedoEnabled(False)
        self.outputEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.outputEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.outputEdit.setObjectName("outputEdit")
        self.verticalLayout.addWidget(self.outputEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eraseButton = QtWidgets.QPushButton(FlashDialog)
        self.eraseButton.setObjectName("eraseButton")
        self.horizontalLayout_3.addWidget(self.eraseButton)
        self.flashButton = QtWidgets.QPushButton(FlashDialog)
        self.flashButton.setObjectName("flashButton")
        self.horizontalLayout_3.addWidget(self.flashButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(FlashDialog)
        QtCore.QMetaObject.connectSlotsByName(FlashDialog)

    def retranslateUi(self, FlashDialog):
        _translate = QtCore.QCoreApplication.translate
        FlashDialog.setWindowTitle(_translate("FlashDialog", "Flash Firmware"))
        self.label.setText(_translate("FlashDialog", "Python2 path"))
        self.pickPythonButton.setText(_translate("FlashDialog", "Pick"))
        self.label_2.setText(_translate("FlashDialog", "Firmware file"))
        self.pickFirmwareButton.setText(_translate("FlashDialog", "Pick"))
        self.label_4.setText(_translate("FlashDialog", "Port"))
        self.wiringButton.setText(_translate("FlashDialog", "Wiring instructions"))
        self.label_3.setText(_translate("FlashDialog", "Flasher output:"))
        self.eraseButton.setText(_translate("FlashDialog", "Erase"))
        self.flashButton.setText(_translate("FlashDialog", "Flash"))

